M48
; DRILL file {KiCad 7.0.7} date Sun Apr 14 11:19:27 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-04-14T11:19:27+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C6.500
%
G90
G05
T1
X75.5Y-24.5
T2
X62.5Y-37.5
T0
M30
